noise: True  # specify if simulation should be run with or without noise
sampling_rate: 5.  # sampling rate in GHz used internally in the simulation.
speedup:
  minimum_weight_cut: 1.e-5
  min_efield_amplitude: 2
  delta_C_cut: 0.4
propagation:
  ice_model: southpole_2015
  attenuation_model: SP1
  focusing: True
signal:
  model: ARZ2020 
  shower_type: had
trigger:
  noise_temperature: detector  # in Kelvin
  Vrms: null
weights:
  weight_mode: core_mantle_crust # core_mantle_crust: use the three
  #layer earth model, which considers the different densities of the
  #core, mantle and crust. simple: use the simple earth model, which
  #apply a constant earth density
